### ISSUE TITLE
Plugin doesn't work with IL2CPP

### ISSUE THREAD

**Issue by Daztrax** [razerofficial/Unity_SampleApp#3]
Hi, I was trying to implement this plugin to my Unity game, I use the IL2CPP Scripting backend, but it seems that it actually doesn't work with IL2CPP on build, at least for Windows x64, here's what it seems to be the error on the log file of the build.

![image](https://github.com/razerofficial/Unity_SampleApp/assets/69276789/c73d1db4-8af4-4662-b046-31239e54351d)
![image](https://github.com/razerofficial/Unity_SampleApp/assets/69276789/c212c60b-eb24-41ee-bd37-2529f07ffb33)

**Comment by tgraupmann** [comment]
Looks like a preprocessor check could just return true. The idea for that code is to check if the DLL exists before loading it from C#. Similar checking is in the C++ DLL. I'll update the plugin...

**Comment by Daztrax** [comment]
Hi, I already made a solution for Windows for the method IsChromaSDKAvailable(), I'll leave it here in case you want to check it how it now works with IL2CPP

I'll send it as a txt, since it doesnt support to send .cs files

[ChromaAnimationAPI.txt](https://github.com/razerofficial/Unity_SampleApp/files/14397878/ChromaAnimationAPI.txt)

However, if you have a better solution to this for IL2CPP it would be great.

**Comment by tgraupmann** [comment]
@Daztrax Thanks for the code sample.

https://github.com/razerofficial/Unity_SampleApp/commit/e441be0e2352c9b8825e45ec9a5444d63c3c4b91

https://github.com/razerofficial/Unity_SampleApp/commit/16d083d28d6bdbbb11d4213e7b36884af533f951

I put the code behind the preprocessor check.

```
#if ENABLE_IL2CPP
	String productVersion = GetProductVersion(fileName);
```

**Comment by tgraupmann** [comment]
And I switched it to check file version so it's the same logic as the `CChromaEditorLibrary`.
